import turtle
wn = turtle.Screen()
turtle.setup(800, 600)

space = int(turtle.numinput("Grid", "Enter the space of grid: ", "10"))
g = turtle.Turtle()
g.shape("turtle")
g.pensize(3)
g.up()
g.goto(-400, 300)
g.down()
g.speed(10000000000000)

a = int(600 / (space * 2))
for x in range (a):
    g.forward(800)
    g.up()
    g.right(90)
    g.forward(space)
    g.right(90)
    g.down()
    g.forward(800)
    g.up()
    g.left(90)
    g.forward(space)
    g.left(90)
    g.down()

g.left(90)
g.up()
g.forward(space)
g.down()

b = int(800 / (space * 2))
for y in range (b):
    g.forward(600)
    g.up()
    g.right(90)
    g.forward(space)
    g.right(90)
    g.down()
    g.forward(600)
    g.up()
    g.left(90)
    g.forward(space)
    g.left(90)
    g.down()

wn.exitonclick()